### ISSUE TITLE
Pair Review

### ISSUE THREAD

**Issue by amare1990** [Haywayaheadshot/to-do-list-with-webpack-es6#7]
Hi @Haywayaheadshot

Great job so far :+1: 
- Kindly remove the section with class = 'footer-buttons", i.e., your code should follow YAGNI coding style.
- Good modular structure.
- Good job!!!

**Comment by Haywayaheadshot** [comment]
@amare1990 Thank you. I have fixed the issue. Can you check again just to confirm?

**Comment by amare1990** [comment]
- Hi @Haywayaheadshot.  Good Job. You have done all the required changes.
- **CONFIRMED!!!**
